```{r, echo=FALSE}
library(knitr)
opts_chunk$set(error = TRUE)
```

# thefu
Handy corrections for when you fucked up.
Inspired by [nvbn/thefuck](https://github.com/nvbn/thefuck).

## Install
```{r, eval=FALSE}
devtools::install_github("jakob-r/thefuckr")
```
And totally recommended:
Run in command line or edit with your favourite text editor:
```
vi ~/.Rprofile
```
Change the `.Rprofile` so that it has the following lines somewhere.
```
.First = function() {
  if (interactive()) {
    library("thefuckr")
  }
}
```

## Usage
```{r, echo = FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
try(remove.packages("plyr"), silent = TRUE)
try(remove.packages("xtable"), silent = TRUE)
try(remove.packages("xtables"), silent = TRUE)
```

```{r, cache=FALSE}
library(thefu)
# misspelled an installed package?
library(e1061)
fuck()
# thought you already have the package installed?
library(plyr)
fuck()
# That package you don't know if you have it installed or how it is called exactly?
library(xtables)
fuck(confirm = TRUE)
```
